### ISSUE TITLE
Connection timeout in sampling causes sample command to hang

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-store#144]
If doing a sample command (or friends), the following exception can appear:

```
Exception in thread "main" java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:178)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at au.org.ala.biocache.util.LayersStore.samplingStatus(LayersStore.scala:155)
	at au.org.ala.biocache.util.LayersStore.sample(LayersStore.scala:51)
	at au.org.ala.biocache.tool.Sampling.processBatchRemote(Sampling.scala:463)
	at au.org.ala.biocache.tool.Sampling.sampling(Sampling.scala:367)
	at au.org.ala.biocache.tool.Sampling$.main(Sampling.scala:114)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:134)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
```

At this point, the sample process hangs, neither exiting or recovering.

**Comment by charvolant** [comment]
Pull request https://github.com/AtlasOfLivingAustralia/biocache-store/compare/master...charvolant:issue-144
