### ISSUE TITLE
OutOfMemoryError on solr while selecting distinct values for facets

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#157]
The Spot our species Jenkins job killed the Solr server for about 4 hours (from about 11:42pm until the automated daily 4am reboot) and its local stacktrace was as follows:

```
2016-11-02 23:50:02,959 INFO : [IngestTool] - Ingesting resource uid: dr1903
2016-11-02 23:50:02,959 INFO : [IngestTool] - Loading: dr1903
2016-11-02 23:50:03,464 INFO : [DataLoader] - Darwin core headed CSV loading
2016-11-02 23:50:03,565 INFO : [DataLoader] - Downloading zip file from http://ecodata-sightings.ala.org.au/ws/record/csvProject/00ca29af-343c-4de3-995d-c37ecb4fcc5d
2016-11-02 23:50:03,793 INFO : [DataLoader] -  Content-Disposition: attachment; filename="project-00ca29af-343c-4de3-995d-c37ecb4fcc5d.csv"
2016-11-02 23:50:03,793 INFO : [DataLoader] - Creating file: /data/biocache-load/dr1903/dr1903.csv
2016-11-02 23:50:03,796 INFO : [DataLoader] - Downloaded. File size: 
2016-11-02 23:50:03,800 INFO : [DataLoader] - File last modified date: Wed Nov 02 23:50:03 AEDT 2016
2016-11-02 23:50:03,804 INFO : [DataLoader] - Using CSV reader with the following settings quotes: " separator: , escape: \
2016-11-02 23:50:03,806 INFO : [Vocab] - Reading internal vocab file: /dwc.txt
2016-11-02 23:50:04,021 INFO : [DataLoader] - Unique terms: occurrenceID
2016-11-02 23:50:04,021 INFO : [DataLoader] - Column headers: occurrenceID,scientificName,family,kingdom,decimalLatitude,decimalLongitude,eventDate,userId,recordedBy,usingReverseGeocodedLocality,individualCount,submissionMethod,georeferenceProtocol,identificationVerificationStatus,occurrenceRemarks,coordinateUncertaintyInMeters,geodeticDatum,rights,locality,associatedMedia,modified,locationID
2016-11-02 23:50:04,022 INFO : [SolrIndexDAO] - Initialising the solr server http://solr-b3.ala.org.au:8080/solr cloudserver:null solrServer:null
2016-11-02 23:50:04,022 INFO : [SolrIndexDAO] - Initialising connection to SOLR server.....
2016-11-02 23:50:04,186 INFO : [SolrIndexDAO] - Initialising connection to SOLR server - done.
2016-11-02 23:51:29,025 ERROR: [DataLoader] - Error while processing facet fields: java.lang.OutOfMemoryError: GC overhead limit exceeded
org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Error while processing facet fields: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:552)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
	at org.apache.solr.client.solrj.impl.ConcurrentUpdateSolrServer.request(ConcurrentUpdateSolrServer.java:296)
	at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
	at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
	at au.org.ala.biocache.index.SolrIndexDAO.getDistinctValues(SolrIndexDAO.scala:789)
	at au.org.ala.biocache.load.DwcCSVLoader.loadFile(DwcCSVLoader.scala:199)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$loadDirectory$1.apply(DwcCSVLoader.scala:125)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$loadDirectory$1.apply(DwcCSVLoader.scala:123)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.DwcCSVLoader.loadDirectory(DwcCSVLoader.scala:123)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:105)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:97)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.load.DwcCSVLoader.load(DwcCSVLoader.scala:97)
	at au.org.ala.biocache.load.Loader.load(Loader.scala:161)
	at au.org.ala.biocache.load.IngestTool$.ingestResource(IngestTool.scala:101)
	at au.org.ala.biocache.load.IngestTool$$anonfun$main$1.apply(IngestTool.scala:54)
	at au.org.ala.biocache.load.IngestTool$$anonfun$main$1.apply(IngestTool.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.IngestTool$.main(IngestTool.scala:51)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:134)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
Exception in thread "main" org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Error while processing facet fields: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:552)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
	at org.apache.solr.client.solrj.impl.ConcurrentUpdateSolrServer.request(ConcurrentUpdateSolrServer.java:296)
	at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
	at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
	at au.org.ala.biocache.index.SolrIndexDAO.getDistinctValues(SolrIndexDAO.scala:789)
	at au.org.ala.biocache.load.DwcCSVLoader.loadFile(DwcCSVLoader.scala:199)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$loadDirectory$1.apply(DwcCSVLoader.scala:125)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$loadDirectory$1.apply(DwcCSVLoader.scala:123)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.DwcCSVLoader.loadDirectory(DwcCSVLoader.scala:123)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:105)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:97)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.load.DwcCSVLoader.load(DwcCSVLoader.scala:97)
	at au.org.ala.biocache.load.Loader.load(Loader.scala:161)
	at au.org.ala.biocache.load.IngestTool$.ingestResource(IngestTool.scala:101)
	at au.org.ala.biocache.load.IngestTool$$anonfun$main$1.apply(IngestTool.scala:54)
	at au.org.ala.biocache.load.IngestTool$$anonfun$main$1.apply(IngestTool.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.IngestTool$.main(IngestTool.scala:51)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:134)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
```

To view the sequence, you need to tunnel into cassandra-b4 and visit the following URL:

http://localhost:9192/job/Spot%20our%20species/36/console

**Comment by ansell** [comment]
The 11:42pm start time is derived from the outage on Uptime.

The previous job committed successfully to Solr around 11:42, but may have caused the issue per known instances where Solr goes down during live indexing even of small collections:

```
2016-11-02 23:41:43,340 INFO : [IndexRecords] - 44000 >> Last key : dr364|urn:lsid:cs.ala.org.au:Record:8785, records per sec: 368.45984
2016-11-02 23:41:46,074 INFO : [IndexRecords] - 45000 >> Last key : dr364|urn:lsid:cs.ala.org.au:Record:9786, records per sec: 365.76447
2016-11-02 23:43:48,155 INFO : [IndexRecords] - Total indexing time 403.51 seconds
2016-11-02 23:43:48,206 INFO : [SolrIndexDAO] - Performing index commit....
2016-11-02 23:44:30,528 INFO : [SolrIndexDAO] - Performing index commit....done
2016-11-02 23:44:31,536 INFO : [SolrIndexDAO] - >>>> Document count of index: 65799877
2016-11-02 23:44:31,560 INFO : [SolrIndexDAO] - >>>> Document count of index: 65799877
2016-11-02 23:44:31,560 INFO : [SolrIndexDAO] - Finalise finished.
2016-11-02 23:44:31,560 INFO : [IngestTool] - Finished ingest for: dr364
```
