### ISSUE TITLE
Resample stalled indefinitely after EOF IOException

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#170]
An attempted full resample in December stalled indefinitely with an IOException caused by an unexpected EOF.

http://localhost:9192/job/Sample%20+%20reprocess%20all/2/console

```
2016-12-23 13:11:54,607 INFO : [BulkProcessor] - Finished loading: /data/tmp/sampling-all.txt1800000 in 172851ms
Exception in thread "main" java.io.IOException: Premature EOF
	at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
	at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3066)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.readLine(BufferedReader.java:317)
	at java.io.BufferedReader.readLine(BufferedReader.java:382)
	at au.com.bytecode.opencsv.CSVReader.getNextLine(CSVReader.java:266)
	at au.com.bytecode.opencsv.CSVReader.readNext(CSVReader.java:233)
	at au.org.ala.biocache.tool.Sampling.processBatchRemote(Sampling.scala:491)
	at au.org.ala.biocache.tool.Sampling.sampling(Sampling.scala:368)
	at au.org.ala.biocache.tool.Sampling$.main(Sampling.scala:115)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:134)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
```

**Comment by ansell** [comment]
Refs https://github.com/AtlasOfLivingAustralia/maintenance/issues/35
