### ISSUE TITLE
Lat/Long not being validated properly

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#172]
A stack trace during a full reprocess indicates that lat/long values are not being validated properly to identify and isolate bad values. In this case, the values are "-0,8333" and "131,2833", which is valid in Europe, but does not match Australian/American decimal usage, which would be "-0.8333" and "131.2833". The spatial server is right to return HTTP 400, as the query should not have been attempted in the first place by either sds or biocache-store.

```
2017-01-11 09:59:18,499 ERROR: [ValidationUtils] - Problem getting zone from lat/long
java.io.IOException: Server returned HTTP response code: 400 for URL: http://spatial.ala.org.au/layers-service/intersect/cl927,cl23,cl937,cl941,cl938,cl939,cl936,cl940,cl963,cl962,cl961,cl960,cl964,cl965,cl22,cl932/-0,8333/131,2833
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at au.org.ala.sds.util.GeoLocationHelper.getZonesContainingPoint(GeoLocationHelper.java:65)
	at au.org.ala.sds.util.ValidationUtils.validateLocation(ValidationUtils.java:40)
	at au.org.ala.sds.validation.PlantPestService.validate(PlantPestService.java:56)
	at au.org.ala.sds.SensitiveDataService.testMapDetails(SensitiveDataService.java:76)
	at au.org.ala.biocache.processor.LocationProcessor.processSensitivity(LocationProcessor.scala:1034)
	at au.org.ala.biocache.processor.LocationProcessor.process(LocationProcessor.scala:90)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:101)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:98)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at au.org.ala.biocache.processor.Processors$.foreach(Processors.scala:12)
	at au.org.ala.biocache.processor.RecordProcessor.processRecord(RecordProcessor.scala:98)
	at au.org.ala.biocache.index.ProcessRecordsRunner$$anonfun$run$6.apply(IndexRecordMultiThreaded.scala:399)
	at au.org.ala.biocache.index.ProcessRecordsRunner$$anonfun$run$6.apply(IndexRecordMultiThreaded.scala:392)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessed$1.apply(OccurrenceDAOImpl.scala:422)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessed$1.apply(OccurrenceDAOImpl.scala:417)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:344)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:336)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOver(CassandraPersistenceManager.scala:336)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOverAll(CassandraPersistenceManager.scala:482)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.pageOverRawProcessed(OccurrenceDAOImpl.scala:417)
	at au.org.ala.biocache.index.ProcessRecordsRunner.run(IndexRecordMultiThreaded.scala:392)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ansell** [comment]
In another case, the values for lat long are "false" and "false":

```
2017-01-10 20:39:52,114 INFO : [BulkProcessor] - [Processor Thread 1] 13888000 >> Last key : dr1097|958658.00, records per sec: 295.68304
2017-01-10 20:39:54,213 INFO : [BulkProcessor] - [Processor Thread 7] 13889000 >> Last key : dr571|42234|"Ixobrychus dubius", records per sec: 476.6444
2017-01-10 20:39:57,442 INFO : [BulkProcessor] - [Processor Thread 5] 13890000 >> Last key : dr368|Australian Bird & Bat Banding Scheme-8535115, records per sec: 309.6934
2017-01-10 20:39:58,110 INFO : [BulkProcessor] - [Processor Thread 6] 13891000 >> Last key : dr376|CANB|CANB68669.1, records per sec: 1497.006
2017-01-10 20:40:02,956 INFO : [BulkProcessor] - [Processor Thread 3] 13892000 >> Last key : dr348|WAM|REPT|R156149, records per sec: 206.35574
2017-01-10 20:40:06,268 INFO : [BulkProcessor] - [Processor Thread 0] 13893000 >> Last key : dr1089|168695|187|, records per sec: 301.93237
2017-01-10 20:40:06,886 INFO : [BulkProcessor] - [Processor Thread 5] 13894000 >> Last key : dr368|Australian Bird & Bat Banding Scheme-8536294, records per sec: 1618.123
2017-01-10 20:40:09,925 INFO : [BulkProcessor] - [Processor Thread 2] 13895000 >> Last key : dr2009|URN:CornellLabOfOrnithology:EBIRD:OBS346478125, records per sec: 329.1639
2017-01-10 20:40:10,360 INFO : [BulkProcessor] - [Processor Thread 4] 13896000 >> Last key : dr359|Pomatostomus temporalis|175141, records per sec: 2298.8506
2017-01-10 20:40:11,353 INFO : [BulkProcessor] - [Processor Thread 7] 13897000 >> Last key : dr571|42245|"Geopelia humeralis", records per sec: 1007.0494
2017-01-10 20:40:11,559 ERROR: [ValidationUtils] - Problem getting zone from lat/long
java.io.IOException: Server returned HTTP response code: 400 for URL: http://spatial.ala.org.au/layers-service/intersect/cl927,cl23,cl937,cl941,cl938,cl939,cl936,cl940,cl963,cl962,cl961,cl960,cl964,cl965,cl22,cl932/false/false
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at au.org.ala.sds.util.GeoLocationHelper.getZonesContainingPoint(GeoLocationHelper.java:65)
	at au.org.ala.sds.util.ValidationUtils.validateLocation(ValidationUtils.java:40)
	at au.org.ala.sds.validation.PlantPestService.validate(PlantPestService.java:56)
	at au.org.ala.sds.SensitiveDataService.testMapDetails(SensitiveDataService.java:76)
	at au.org.ala.biocache.processor.LocationProcessor.processSensitivity(LocationProcessor.scala:1034)
	at au.org.ala.biocache.processor.LocationProcessor.process(LocationProcessor.scala:90)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:101)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:98)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at au.org.ala.biocache.processor.Processors$.foreach(Processors.scala:12)
	at au.org.ala.biocache.processor.RecordProcessor.processRecord(RecordProcessor.scala:98)
	at au.org.ala.biocache.index.ProcessRecordsRunner$$anonfun$run$6.apply(IndexRecordMultiThreaded.scala:399)
	at au.org.ala.biocache.index.ProcessRecordsRunner$$anonfun$run$6.apply(IndexRecordMultiThreaded.scala:392)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessed$1.apply(OccurrenceDAOImpl.scala:422)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessed$1.apply(OccurrenceDAOImpl.scala:417)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:344)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:336)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOver(CassandraPersistenceManager.scala:336)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOverAll(CassandraPersistenceManager.scala:482)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.pageOverRawProcessed(OccurrenceDAOImpl.scala:417)
	at au.org.ala.biocache.index.ProcessRecordsRunner.run(IndexRecordMultiThreaded.scala:392)
	at java.lang.Thread.run(Thread.java:745)
```
