### ISSUE TITLE
ANWC import contains NullPointerExceptions

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#174]
The ANWC (dr341) import contains NullPointerException's that may be preventing it from importing all records. Investigating the difference in record counts between the ANWC records and the Biocache and found this.

```
2017-01-04 04:53:34,018 ERROR: [RecordProcessor] - Error processing record batch with length: '50',  sleeping for 20 secs before retries
java.lang.NullPointerException
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$getCombinedUserStatus$2$$anonfun$apply$18.apply(OccurrenceDAOImpl.scala:995)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$getCombinedUserStatus$2$$anonfun$apply$18.apply(OccurrenceDAOImpl.scala:995)
	at scala.collection.IndexedSeqOptimized$$anonfun$exists$1.apply(IndexedSeqOptimized.scala:40)
	at scala.collection.IndexedSeqOptimized$$anonfun$exists$1.apply(IndexedSeqOptimized.scala:40)
	at scala.collection.IndexedSeqOptimized$class.segmentLength(IndexedSeqOptimized.scala:189)
	at scala.collection.mutable.ArrayBuffer.segmentLength(ArrayBuffer.scala:47)
	at scala.collection.GenSeqLike$class.prefixLength(GenSeqLike.scala:92)
	at scala.collection.AbstractSeq.prefixLength(Seq.scala:40)
	at scala.collection.IndexedSeqOptimized$class.exists(IndexedSeqOptimized.scala:40)
	at scala.collection.mutable.ArrayBuffer.exists(ArrayBuffer.scala:47)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$getCombinedUserStatus$2.apply(OccurrenceDAOImpl.scala:995)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$getCombinedUserStatus$2.apply(OccurrenceDAOImpl.scala:995)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.getCombinedUserStatus(OccurrenceDAOImpl.scala:995)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.convertAssertionsToMap(OccurrenceDAOImpl.scala:681)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$updateOccurrenceBatch$2.apply(OccurrenceDAOImpl.scala:646)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$updateOccurrenceBatch$2.apply(OccurrenceDAOImpl.scala:607)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.updateOccurrenceBatch(OccurrenceDAOImpl.scala:607)
	at au.org.ala.biocache.processor.RecordProcessor.writeProcessBatch(RecordProcessor.scala:136)
	at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1.applyOrElse(ProcessRecords.scala:340)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at scala.actors.ReactorTask.run(ReactorTask.scala:31)
	at scala.actors.Reactor$class.resumeReceiver(Reactor.scala:129)
	at au.org.ala.biocache.tool.Consumer.scala$actors$InternalReplyReactor$$super$resumeReceiver(ProcessRecords.scala:304)
	at scala.actors.InternalReplyReactor$class.resumeReceiver(InternalReplyReactor.scala:59)
	at au.org.ala.biocache.tool.Consumer.resumeReceiver(ProcessRecords.scala:304)
	at scala.actors.InternalActor$class.searchMailbox(InternalActor.scala:76)
	at au.org.ala.biocache.tool.Consumer.searchMailbox(ProcessRecords.scala:304)
	at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Reactor.scala:117)
	at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:114)
	at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:114)
	at scala.actors.ReactorTask.run(ReactorTask.scala:33)
	at scala.actors.ReactorTask.compute(ReactorTask.scala:63)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ansell** [comment]
This may also be happening in other cases, with the following appearing in the currently executing full reprocess:

```
2017-01-11 04:01:07,314 INFO : [BulkProcessor] - [Processor Thread 1] 25331000 >> Last key : dr165|AADC|WoV|WoV-190525, records per sec: 17241.379
2017-01-11 04:01:07,481 INFO : [BulkProcessor] - [Processor Thread 3] 25332000 >> Last key : dr359|Aphelocephala leucopsis|27537, records per sec: 5988.024
2017-01-11 04:01:11,627 INFO : [BulkProcessor] - [Processor Thread 4] 25333000 >> Last key : dr359|Sugomel niger|797165, records per sec: 241.19633
2017-01-11 04:01:11,896 INFO : [BulkProcessor] - [Processor Thread 6] 25334000 >> Last key : dr376|MEL|MEL0060310A, records per sec: 3717.4722
2017-01-11 04:01:13,155 INFO : [BulkProcessor] - [Processor Thread 7] 25335000 >> Last key : dr571|89989|"Acanthagenys rufogularis, records per sec: 794.2812
2017-01-11 04:01:15,324 INFO : [BulkProcessor] - [Processor Thread 5] 25336000 >> Last key : dr368|SEMMI0046950, records per sec: 461.04196
2017-01-11 04:01:15,440 INFO : [BulkProcessor] - [Processor Thread 2] 25337000 >> Last key : dr2009|URN:CornellLabOfOrnithology:EBIRD:OBS392036241, records per sec: 8620.689
2017-01-11 04:01:20,050 INFO : [BulkProcessor] - [Processor Thread 0] 25338000 >> Last key : dr1089|96726|226|, records per sec: 216.91974
2017-01-11 04:01:20,316 INFO : [BulkProcessor] - [Processor Thread 3] 25339000 >> Last key : dr359|Aphelocephala leucopsis|39999, records per sec: 3759.3984
2017-01-11 04:01:20,650 INFO : [BulkProcessor] - [Processor Thread 7] 25340000 >> Last key : dr571|90006|"Pomatostomus superciliosus", records per sec: 2994.012
2017-01-11 04:01:23,121 INFO : [BulkProcessor] - [Processor Thread 6] 25341000 >> Last key : dr376|MEL|MEL0061295A, records per sec: 404.69446
2017-01-11 04:01:24,733 INFO : [BulkProcessor] - [Processor Thread 5] 25342000 >> Last key : dr368|SEMMI0047951, records per sec: 620.3474
2017-01-11 04:01:29,771 INFO : [BulkProcessor] - [Processor Thread 7] 25343000 >> Last key : dr571|90030|"Manorina flavigula", records per sec: 198.49146
2017-01-11 04:01:30,352 INFO : [BulkProcessor] - [Processor Thread 2] 25344000 >> Last key : dr2009|URN:CornellLabOfOrnithology:EBIRD:OBS392038343, records per sec: 1721.1705
2017-01-11 04:01:32,719 INFO : [BulkProcessor] - [Processor Thread 0] 25345000 >> Last key : dr1089|96748|364|, records per sec: 422.47568
2017-01-11 04:01:34,025 INFO : [BulkProcessor] - [Processor Thread 3] 25346000 >> Last key : dr359|Aphelocephala leucopsis|451010, records per sec: 765.6968
2017-01-11 04:01:35,008 INFO : [BulkProcessor] - [Processor Thread 6] 25347000 >> Last key : dr376|MEL|MEL0062277A, records per sec: 1017.294
2017-01-11 04:01:35,443 INFO : [BulkProcessor] - [Processor Thread 5] 25348000 >> Last key : dr368|SEMMI0048951, records per sec: 2298.8506
2017-01-11 04:01:36,935 INFO : [BulkProcessor] - [Processor Thread 4] 25349000 >> Last key : dr359|Sula leucogaster|420072, records per sec: 670.2413
2017-01-11 04:01:38,314 INFO : [BulkProcessor] - [Processor Thread 7] 25350000 >> Last key : dr571|90062|"Colluricincla harmonica ", records per sec: 725.1632
2017-01-11 04:01:39,619 ERROR: [RecordProcessor] - Error processing record batch with length: '200',  sleeping for 20 secs before retries
java.lang.NullPointerException
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$getCombinedUserStatus$2$$anonfun$apply$18.apply(OccurrenceDAOImpl.scala:995)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$getCombinedUserStatus$2$$anonfun$apply$18.apply(OccurrenceDAOImpl.scala:995)
	at scala.collection.IndexedSeqOptimized$$anonfun$exists$1.apply(IndexedSeqOptimized.scala:40)
	at scala.collection.IndexedSeqOptimized$$anonfun$exists$1.apply(IndexedSeqOptimized.scala:40)
	at scala.collection.IndexedSeqOptimized$class.segmentLength(IndexedSeqOptimized.scala:189)
	at scala.collection.mutable.ArrayBuffer.segmentLength(ArrayBuffer.scala:47)
	at scala.collection.GenSeqLike$class.prefixLength(GenSeqLike.scala:92)
	at scala.collection.AbstractSeq.prefixLength(Seq.scala:40)
	at scala.collection.IndexedSeqOptimized$class.exists(IndexedSeqOptimized.scala:40)
	at scala.collection.mutable.ArrayBuffer.exists(ArrayBuffer.scala:47)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$getCombinedUserStatus$2.apply(OccurrenceDAOImpl.scala:995)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$getCombinedUserStatus$2.apply(OccurrenceDAOImpl.scala:995)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.getCombinedUserStatus(OccurrenceDAOImpl.scala:995)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.convertAssertionsToMap(OccurrenceDAOImpl.scala:681)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$updateOccurrenceBatch$2.apply(OccurrenceDAOImpl.scala:646)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$updateOccurrenceBatch$2.apply(OccurrenceDAOImpl.scala:607)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.updateOccurrenceBatch(OccurrenceDAOImpl.scala:607)
	at au.org.ala.biocache.processor.RecordProcessor.writeProcessBatch(RecordProcessor.scala:136)
	at au.org.ala.biocache.index.ProcessRecordsRunner$$anonfun$run$6.apply(IndexRecordMultiThreaded.scala:396)
	at au.org.ala.biocache.index.ProcessRecordsRunner$$anonfun$run$6.apply(IndexRecordMultiThreaded.scala:392)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessed$1.apply(OccurrenceDAOImpl.scala:422)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessed$1.apply(OccurrenceDAOImpl.scala:417)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:344)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:336)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOver(CassandraPersistenceManager.scala:336)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOverAll(CassandraPersistenceManager.scala:482)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.pageOverRawProcessed(OccurrenceDAOImpl.scala:417)
	at au.org.ala.biocache.index.ProcessRecordsRunner.run(IndexRecordMultiThreaded.scala:392)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ansell** [comment]
I am having trouble conceptualising how this bug could occur, possibly due to my lack of familiarity with Scala semantics.

The errors always seem to be appearing on line 995:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/349791afaa15c8e3c22a288f8a686304b967ed6c/src/main/scala/au/org/ala/biocache/dao/OccurrenceDAOImpl.scala#L995

However, there is a very similar instruction on line 991 that should execute successfully before it (assuming Scala executes it immediately):

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/349791afaa15c8e3c22a288f8a686304b967ed6c/src/main/scala/au/org/ala/biocache/dao/OccurrenceDAOImpl.scala#L991

The most interesting anomaly seems to be that the sorted list is not iterated on the second time, (although there doesn't seem to be any requirement for not using it), leaving open the possibility that if there are nulls that are sorted last in the sorted list, that they may be appearing earlier in the unsorted version, and interfering with the exists predicate. The bigger issue would be why the collection has null values inserted into it, given that qa.code is always dereferenced for items before inserting them into the list.

**Comment by ansell** [comment]
I attempted to verify the record that may have been causing the issue using process-uuids, but was unable to replicate the error. Ie, using process-uuids none of the row keys trigger any errors associated with annotations.
