### ISSUE TITLE
Index threw a number of SolrException unknown field license errors

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#182]
The complete reindex over the weekend was the first to use an updated version of biocache-store since September 2016. 

It started to throw some new errors of the following type:

```
2017-01-21 03:14:37,658 ERROR: [SolrCore] - org.apache.solr.common.SolrException: ERROR: [doc=16f50ef8-3776-4dd5-bfaf-706982b60a7e] unknown field 'license'
	at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:185)
	at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:78)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:238)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:164)
	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:69)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:51)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:926)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1080)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:692)
	at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:247)
	at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:174)
	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:99)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:74)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:1976)
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:150)
	at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:124)
	at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:68)
	at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:54)
	at au.org.ala.biocache.index.SolrIndexDAO.indexFromMap(SolrIndexDAO.scala:698)
	at au.org.ala.biocache.index.IndexRunner$$anonfun$run$7.apply(IndexRecordMultiThreaded.scala:567)
	at au.org.ala.biocache.index.IndexRunner$$anonfun$run$7.apply(IndexRecordMultiThreaded.scala:555)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:344)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:336)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOver(CassandraPersistenceManager.scala:336)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOverAll(CassandraPersistenceManager.scala:482)
	at au.org.ala.biocache.index.IndexRunner.run(IndexRecordMultiThreaded.scala:555)
	at java.lang.Thread.run(Thread.java:745)

2017-01-21 03:14:37,660 ERROR: [IndexRunner] - Problem indexing record: dr364|04723086-fd89-4d55-ac3a-ca857278566f ERROR: [doc=16f50ef8-3776-4dd5-bfaf-706982b60a7e] unknown field 'license'
```

@djtfmartin , is this related to your change in November: https://github.com/AtlasOfLivingAustralia/biocache-store/commit/788045a29cbf34926cf13e8b47cb8bd0137a23cd

The last commit on the version from September that was in use is:

https://github.com/AtlasOfLivingAustralia/biocache-store/commit/349791afaa15c8e3c22a288f8a686304b967ed6c

The total commit range therefore (including some changes back to March 2016) is:

https://github.com/AtlasOfLivingAustralia/biocache-store/compare/349791afaa15c8e3c22a288f8a686304b967ed6c...83442e2634df4520fec3c20120a29764f74090fc

**Comment by ansell** [comment]
The deployed version on cassandra-b4 has been rolled back to https://github.com/AtlasOfLivingAustralia/biocache-store/commit/349791afaa15c8e3c22a288f8a686304b967ed6c

**Comment by adam-collins** [comment]
A new schema.xml field was required. https://github.com/AtlasOfLivingAustralia/ala-install/commit/168f41ee02457f7a02622d4ab22402511f1b4c96
