### ISSUE TITLE
NumberFormatException thrown when sensitive data records do not have coordinates

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#192]
There is a NumberFormatException thrown when sensitive data records do not have coordinates. The policy for dealing with SDS records that do not have coordinates needs to be clarified and matched to code to ensure that they are still properly desensitized in the necessary cases.

The stacktrace detailing where the code exception propagates back out of the processor is:

```
2017-03-02 12:14:46,089 ERROR: [RecordProcessor] - Error processing record: drXYZ|ABC, empty String
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1020)
	at java.lang.Float.parseFloat(Float.java:452)
	at scala.collection.immutable.StringLike$class.toFloat(StringLike.scala:231)
	at scala.collection.immutable.StringOps.toFloat(StringOps.scala:31)
	at au.org.ala.biocache.caches.LocationDAO$.getLatLongKey(LocationDAO.scala:73)
	at au.org.ala.biocache.caches.LocationDAO$.storePointForSampling(LocationDAO.scala:85)
	at au.org.ala.biocache.processor.SensitivityProcessor.process(SensitivityProcessor.scala:211)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:79)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:75)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at au.org.ala.biocache.processor.Processors$.foreach(Processors.scala:12)
	at au.org.ala.biocache.processor.RecordProcessor.processRecord(RecordProcessor.scala:75)
	at au.org.ala.biocache.tool.Consumer.act(ProcessRecords.scala:275)
	at scala.actors.Reactor$$anonfun$dostart$1.apply(Reactor.scala:224)
	at scala.actors.Reactor$$anonfun$dostart$1.apply(Reactor.scala:224)
	at scala.actors.ReactorTask.run(ReactorTask.scala:33)
	at scala.actors.ReactorTask.compute(ReactorTask.scala:63)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ansell** [comment]
If the records do not have coordinates the policy is still to obfuscate the rest of the information. In any case, the NumberFormatException should either be avoided or handled specifically, as in its current state the code may not be populating the informationWitheld correctly in the SensitivityProcessor class:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/processor/SensitivityProcessor.scala#L211

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/processor/SensitivityProcessor.scala#L223

 if it exits the method at the point it does. 

It may also not be fully processing the method if the exception is stopping the results from being stored:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/processor/RecordProcessor.scala#L99
