### ISSUE TITLE
NumberFormatException thrown in date parsing

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-store#21]
```
Exception in thread "Thread-4" java.lang.NumberFormatException: For input string: "0 01"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
        at au.org.ala.biocache.parser.DateParser$.isValid(DateParser.scala:116)
        at au.org.ala.biocache.parser.DateParser$.parseDate(DateParser.scala:28)
        at au.org.ala.biocache.processor.EventProcessor.process(EventProcessor.scala:166)
        at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:96)
        at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:95)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
        at au.org.ala.biocache.processor.Processors$.foreach(Processors.scala:10)
        at au.org.ala.biocache.processor.RecordProcessor.processRecord(RecordProcessor.scala:95)
        at au.org.ala.biocache.index.ProcessRecordsRunner$$anonfun$run$6.apply(IndexRecordMultiThreaded.scala:388)
        at au.org.ala.biocache.index.ProcessRecordsRunner$$anonfun$run$6.apply(IndexRecordMultiThreaded.scala:385)
        at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessed$1.apply(OccurrenceDAOImpl.scala:342)
        at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessed$1.apply(OccurrenceDAOImpl.scala:337)
        at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:341)
        at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:333)
        at scala.collection.immutable.List.foreach(List.scala:318)
:
```

**Comment by djtfmartin** [comment]
this is now fixed
