### ISSUE TITLE
Error during sampling leaves a non-daemon blocked thread, preventing JVM termination

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#244]
Errors during sampling leave a non-daemon blocked ``LoadSamplingConsumer`` thread, which prevents JVM termination. The thread needs to be interrupted when failures occur on the main thread.

The error thrown in this case is a ``NullPointerException`` due to missing ``biocache-store`` error handling after a failed web-service call to the sampling server:

```
2018-04-14 04:09:35,910 INFO : [PointsReader] - Loading points from file: /data/tmp/loc-dr364.txt
2018-04-14 04:11:51,092 ERROR: [LayersStore] - Failed to download from download_url: {"progress":480,"progressMessage":"Finished sampling layer: world. Points processed: 45288","error":"No space left on device","status":"error","points":90576,"started":"14/04/18 04:08:56:733","fields":481}
Exception in thread "main" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.BufferedReader.<init>(BufferedReader.java:101)
	at java.io.BufferedReader.<init>(BufferedReader.java:116)
	at au.com.bytecode.opencsv.CSVReader.<init>(CSVReader.java:193)
	at au.com.bytecode.opencsv.CSVReader.<init>(CSVReader.java:171)
	at au.com.bytecode.opencsv.CSVReader.<init>(CSVReader.java:117)
	at au.com.bytecode.opencsv.CSVReader.<init>(CSVReader.java:56)
	at au.org.ala.biocache.tool.Sampling.processBatchRemote(Sampling.scala:513)
	at au.org.ala.biocache.tool.Sampling.sampling(Sampling.scala:412)
	at au.org.ala.biocache.tool.Sampling$.main(Sampling.scala:113)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:134)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
```

Running jstack on the process shows the cause of non-termination as a ``LoadSamplingConsumer`` thread waiting permanently on ``LinkedBlockingQueue.take()`` and preventing the JVM termination because it has not been terminated by the failure above:

```
$ sudo jstack -F -l 16934
Attaching to process ID 16934, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.161-b12
Deadlock Detection:

No deadlocks found.

Thread 16941: (state = BLOCKED)

Locked ownable synchronizers:
    - None

Thread 16984: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Interpreted frame)
 - java.util.concurrent.locks.LockSupport.park(java.lang.Object) @bci=14, line=175 (Interpreted frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await() @bci=42, line=2039 (Interpreted frame)
 - java.util.concurrent.LinkedBlockingQueue.take() @bci=29, line=442 (Interpreted frame)
 - au.org.ala.biocache.tool.LoadSamplingConsumer.run() @bci=4, line=660 (Interpreted frame)

Locked ownable synchronizers:
    - None

Thread 16973: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.LockSupport.parkNanos(java.lang.Object, long) @bci=20, line=215 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(long) @bci=78, line=2078 (Compiled frame)
 - java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take() @bci=124, line=1093 (Compiled frame)
 - java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take() @bci=1, line=809 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor.getTask() @bci=149, line=1074 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=26, line=1134 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=624 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=748 (Interpreted frame)

Locked ownable synchronizers:
    - None

Thread 16966: (state = BLOCKED)

Locked ownable synchronizers:
    - None

Thread 16965: (state = BLOCKED)

Locked ownable synchronizers:
    - None

Thread 16964: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Interpreted frame)
 - java.lang.ref.ReferenceQueue.remove(long) @bci=59, line=143 (Compiled frame)
 - java.lang.ref.ReferenceQueue.remove() @bci=2, line=164 (Compiled frame)
 - java.lang.ref.Finalizer$FinalizerThread.run() @bci=36, line=209 (Interpreted frame)

Locked ownable synchronizers:
    - None

Thread 16963: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Interpreted frame)
 - java.lang.Object.wait() @bci=2, line=502 (Compiled frame)
 - java.lang.ref.Reference.tryHandlePending(boolean) @bci=54, line=191 (Compiled frame)
 - java.lang.ref.Reference$ReferenceHandler.run() @bci=1, line=153 (Interpreted frame)

Locked ownable synchronizers:
    - None
```

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
