### ISSUE TITLE
Biocache load command that fails due to directory permissions error exits normally

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#254]
A call to ``biocache load`` that failed because it didn't have permissions to the directory due to an ansible bug, https://github.com/AtlasOfLivingAustralia/ala-install/issues/172 , exited normally and Jenkins took that to mean it was successful. This is an issue as we rely on automated jenkins load jobs to fail to give us notification that there is a problem that needs to be looked into. The log messages in Jenkins were the following (with some redactions):

```
aws-bstore-1b 2018-05-30 14:36:18,450 INFO : [DataLoader] - SFTP the most recent from sftp://...../dr364
aws-bstore-1b 2018-05-30 14:36:19,099 ERROR: [SFTPTools] - Unable to SCP biocollect/dr364/dr364-20180529-230013.dwc.csv
java.io.IOException: Unable to create directory /data/biocache-load/dr364/biocollect/dr364
	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2472)
	at au.org.ala.biocache.util.SFTPTools$.scpFile(SFTPTools.scala:112)
	at au.org.ala.biocache.util.SFTPTools$.sftpLatestArchive(SFTPTools.scala:53)
	at au.org.ala.biocache.load.DataLoader$class.fileDetails$1(DataLoader.scala:430)
	at au.org.ala.biocache.load.DataLoader$class.downloadSFTPArchive(DataLoader.scala:432)
	at au.org.ala.biocache.load.DwcCSVLoader.downloadSFTPArchive(DwcCSVLoader.scala:85)
	at au.org.ala.biocache.load.DataLoader$class.downloadArchive(DataLoader.scala:370)
	at au.org.ala.biocache.load.DwcCSVLoader.downloadArchive(DwcCSVLoader.scala:85)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:111)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:110)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.load.DwcCSVLoader.load(DwcCSVLoader.scala:110)
	at au.org.ala.biocache.load.Loader.load(Loader.scala:202)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:96)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:96)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.Loader$.main(Loader.scala:95)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:133)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
aws-bstore-1b 2018-05-30 14:36:19,105 INFO : [DataLoader] - Unable to extract a new file for dr364 at sftp://...../dr364
aws-bstore-1b 2018-05-30 14:36:19,105 INFO : [DataLoader] - File last modified date: null
aws-bstore-1b 2018-05-30 14:36:19,377 INFO : [DataLoader] - Registry response code: 200
aws-bstore-1b 2018-05-30 14:36:19,377 INFO : [Loader] - Completed loading resource: dr364
Finished: SUCCESS
```

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
