### ISSUE TITLE
NullPointerException during SensitivityProcessor

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#258]
A reprocess on aws-bstore-3b has the following NullPointerException in its log file for a particular rowkey ``67ef69e0-ec7e-4162-9f2f-816db560ef1d``:

```
aws-bstore-3b 2018-06-08 07:30:40,849 ERROR: [Cassandra3PersistenceManager] - Problem persisting the following to occ - null
java.lang.NullPointerException
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$9.apply(Cassandra3PersistenceManager.scala:490)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$9.apply(Cassandra3PersistenceManager.scala:490)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.createPutStatement(Cassandra3PersistenceManager.scala:490)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.put(Cassandra3PersistenceManager.scala:414)
	at au.org.ala.biocache.processor.SensitivityProcessor.process(SensitivityProcessor.scala:253)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:84)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:78)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at au.org.ala.biocache.processor.Processors$.foreach(Processors.scala:12)
	at au.org.ala.biocache.processor.RecordProcessor.processRecord(RecordProcessor.scala:78)
	at au.org.ala.biocache.tool.ProcessLocalRecords$$anonfun$7.apply(ProcessLocalRecords.scala:149)
	at au.org.ala.biocache.tool.ProcessLocalRecords$$anonfun$7.apply(ProcessLocalRecords.scala:140)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessedLocal$2.apply(OccurrenceDAOImpl.scala:487)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessedLocal$2.apply(OccurrenceDAOImpl.scala:482)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$pageOverLocalNotAsync$1$$anon$4$$anonfun$call$2.apply(Cassandra3PersistenceManager.scala:950)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$pageOverLocalNotAsync$1$$anon$4$$anonfun$call$2.apply(Cassandra3PersistenceManager.scala:884)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$pageOverLocalNotAsync$1$$anon$4.call(Cassandra3PersistenceManager.scala:884)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$pageOverLocalNotAsync$1$$anon$4.call(Cassandra3PersistenceManager.scala:793)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
aws-bstore-3b 2018-06-08 07:30:40,850 ERROR: [Cassandra3PersistenceManager] - verbatimLocality = 
aws-bstore-3b 2018-06-08 07:30:40,850 ERROR: [Cassandra3PersistenceManager] - originalSensitiveValues = 
aws-bstore-3b 2018-06-08 07:30:40,850 ERROR: [Cassandra3PersistenceManager] - locality = 
aws-bstore-3b 2018-06-08 07:30:40,850 ERROR: [Cassandra3PersistenceManager] - decimalLongitude = null
aws-bstore-3b 2018-06-08 07:30:40,850 ERROR: [Cassandra3PersistenceManager] - decimalLatitude = null
aws-bstore-3b 2018-06-08 07:30:40,850 WARN : [RecordProcessor] - Non-fatal error processing record: 67ef69e0-ec7e-4162-9f2f-816db560ef1d, processorName: sensitive, error: null
java.lang.NullPointerException
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$9.apply(Cassandra3PersistenceManager.scala:490)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$9.apply(Cassandra3PersistenceManager.scala:490)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.createPutStatement(Cassandra3PersistenceManager.scala:490)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.put(Cassandra3PersistenceManager.scala:414)
	at au.org.ala.biocache.processor.SensitivityProcessor.process(SensitivityProcessor.scala:253)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:84)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:78)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at au.org.ala.biocache.processor.Processors$.foreach(Processors.scala:12)
	at au.org.ala.biocache.processor.RecordProcessor.processRecord(RecordProcessor.scala:78)
	at au.org.ala.biocache.tool.ProcessLocalRecords$$anonfun$7.apply(ProcessLocalRecords.scala:149)
	at au.org.ala.biocache.tool.ProcessLocalRecords$$anonfun$7.apply(ProcessLocalRecords.scala:140)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessedLocal$2.apply(OccurrenceDAOImpl.scala:487)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessedLocal$2.apply(OccurrenceDAOImpl.scala:482)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$pageOverLocalNotAsync$1$$anon$4$$anonfun$call$2.apply(Cassandra3PersistenceManager.scala:950)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$pageOverLocalNotAsync$1$$anon$4$$anonfun$call$2.apply(Cassandra3PersistenceManager.scala:884)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$pageOverLocalNotAsync$1$$anon$4.call(Cassandra3PersistenceManager.scala:884)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$pageOverLocalNotAsync$1$$anon$4.call(Cassandra3PersistenceManager.scala:793)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ansell** [comment]
http://localhost:9193/job/Complete%20Reprocess/job/Complete%20Reprocess/212/

**Comment by djtfmartin** [comment]
i think this now fixed. Ive test via running on the cluster with

 `biocache process-single 67ef69e0-ec7e-4162-9f2f-816db560ef1d`

and im not seeing this in the logs now (this was happening for quite a few records).
