### ISSUE TITLE
IndexingTest "Test range parsing" intermittently fails

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#292]
The IndexingTest "Test range parsing" intermittently fails, including at least once on TravisCI and fairly often locally.

https://travis-ci.org/AtlasOfLivingAustralia/biocache-store/builds/453711673

The line it is failing on seems to be predicated on the total number of results being variable, not failing if more than 10000 records are indexed (even though there are exactly 10000 records in the input set):

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/da151fc525bd24b0bc50cd70926b131e5906ce3c/src/test/scala/au/org/ala/biocache/IndexingTest.scala#L77

```
[ERROR] Tests run: 352, Failures: 0, Errors: 1, Skipped: 18, Time elapsed: 16.724 s <<< FAILURE! - in JUnit Vintage
[ERROR] Test range parsing  Time elapsed: 6.128 s  <<< ERROR!
org.scalatest.exceptions.TestFailedException: Expected true, but got false
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:318)
	at au.org.ala.biocache.ConfigFunSuite.newAssertionFailedException(ConfigFunSuite.scala:15)
	at org.scalatest.Assertions$class.expectResult(Assertions.scala:627)
	at au.org.ala.biocache.ConfigFunSuite.expectResult(ConfigFunSuite.scala:15)
	at au.org.ala.biocache.IndexingTest$$anonfun$1.apply$mcV$sp(IndexingTest.scala:77)
	at au.org.ala.biocache.IndexingTest$$anonfun$1.apply(IndexingTest.scala:17)
	at au.org.ala.biocache.IndexingTest$$anonfun$1.apply(IndexingTest.scala:17)
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
	at au.org.ala.biocache.ConfigFunSuite.withFixture(ConfigFunSuite.scala:15)
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)
	at au.org.ala.biocache.ConfigFunSuite.runTest(ConfigFunSuite.scala:15)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)
	at au.org.ala.biocache.ConfigFunSuite.runTests(ConfigFunSuite.scala:15)
	at org.scalatest.Suite$class.run(Suite.scala:2303)
	at au.org.ala.biocache.ConfigFunSuite.org$scalatest$FunSuite$$super$run(ConfigFunSuite.scala:15)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)
	at au.org.ala.biocache.ConfigFunSuite.run(ConfigFunSuite.scala:15)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:39)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:79)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:70)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:132)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   IndexingTest>ConfigFunSuite.run:15->ConfigFunSuite.org$scalatest$FunSuite$$super$run:15->ConfigFunSuite.runTests:15->ConfigFunSuite.runTest:15->ConfigFunSuite.withFixture:15->ConfigFunSuite.expectResult:15->ConfigFunSuite.newAssertionFailedException:15 » TestFailed
[INFO] 
[ERROR] Tests run: 372, Failures: 0, Errors: 1, Skipped: 18
```

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
