### ISSUE TITLE
Exceptions when loading images with openjdk java

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-store#316]
OpenJDK is not distributed with a complete JAI.

Occurring at  https://github.com/AtlasOfLivingAustralia/biocache-store/blob/65539f4c1290e4a098b0a208b4d4dba7b6cb8029/src/main/scala/au/org/ala/biocache/load/ThumbnailableImage.scala#L26

```
Error: One factory fails for the operation "jpeg"
Occurs in: javax.media.jai.ThreadSafeOperationRegistry
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor622.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
        at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1674)
        at javax.media.jai.ThreadSafeOperationRegistry.invokeFactory(ThreadSafeOperationRegistry.java:473)
        at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
        at com.sun.media.jai.opimage.StreamRIF.create(StreamRIF.java:102)
                                                                                                      77632,2-9     99%
        at au.org.ala.biocache.load.LocalMediaStore$.save(MediaStore.scala:596)
        at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$downloadMedia$1.apply(OccurrenceDAOImpl.scala:588)
        at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$downloadMedia$1.apply(OccurrenceDAOImpl.scala:587)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at au.org.ala.biocache.dao.OccurrenceDAOImpl.downloadMedia(OccurrenceDAOImpl.scala:587)
        at au.org.ala.biocache.processor.RecordProcessor.addRecord(RecordProcessor.scala:198)
        at au.org.ala.biocache.Store$.loadRecord(Store.scala:162)
        at au.org.ala.biocache.Store.loadRecord(Store.scala)
        at au.org.ala.biocache.web.UploaderThread.addRecord(UploadController.java:892)
        at au.org.ala.biocache.web.UploaderThread.loadRecords(UploadController.java:819)
        at au.org.ala.biocache.web.UploaderThread.run(UploadController.java:701)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.media.jai.util.ImagingException: All factories fail for the operation "jpeg"
        at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1687)
        at javax.media.jai.ThreadSafeOperationRegistry.invokeFactory(ThreadSafeOperationRegistry.java:473)
        at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
        at com.sun.media.jai.opimage.StreamRIF.create(StreamRIF.java:102)
        ... 27 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor622.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
                                                                                                      77610,2-9     99%
        at javax.media.jai.ThreadSafeOperationRegistry.invokeFactory(ThreadSafeOperationRegistry.java:473)
        at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
        at com.sun.media.jai.opimage.StreamRIF.create(StreamRIF.java:102)
        ... 27 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor622.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
        at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1674)
        ... 30 more
Caused by: java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/ImageFormatException
        at com.sun.media.jai.codecimpl.JPEGImageDecoder.decodeAsRenderedImage(JPEGImageDecoder.java:46)
        at com.sun.media.jai.opimage.CodecRIFUtil.create(CodecRIFUtil.java:88)
        at com.sun.media.jai.opimage.JPEGRIF.create(JPEGRIF.java:43)
        ... 35 more
Caused by: java.lang.ClassNotFoundException: com.sun.image.codec.jpeg.ImageFormatException
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1859)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1702)
        ... 38 more
```

**Comment by djtfmartin** [comment]
FYI https://github.com/AtlasOfLivingAustralia/ala-install/issues/236

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
