### ISSUE TITLE
NPE when the load starts

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-store#340]
was loading inat second batch (dr1411),  here: http://localhost:9193/job/Cloud%20Infrastructure/job/BSTORE/job/Parameterised%20Load/5052/console
``` 
aws-bstore-4b 2019-09-09 14:09:50,887 INFO : [Vocab] - Reading vocab file: /data/biocache/vocab/mime-types.txt
Exception in thread "Thread-7" java.lang.NullPointerException
	at au.org.ala.biocache.load.RemoteMediaStore$.uploadImageFromUrl(MediaStore.scala:446)
	at au.org.ala.biocache.load.RemoteMediaStore$.save(MediaStore.scala:333)
	at au.org.ala.biocache.load.DataLoader$$anonfun$processMedia$1.apply(DataLoader.scala:323)
	at au.org.ala.biocache.load.DataLoader$$anonfun$processMedia$1.apply(DataLoader.scala:295)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at au.org.ala.biocache.load.DataLoader$class.processMedia(DataLoader.scala:295)
	at au.org.ala.biocache.load.DwCALoader.processMedia(DwCALoader.scala:95)
	at au.org.ala.biocache.load.DwCALoader$PersistConsumer.run(DwCALoader.scala:419)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-14" java.lang.NullPointerException
	at au.org.ala.biocache.load.RemoteMediaStore$.uploadImageFromUrl(MediaStore.scala:446)
	at au.org.ala.biocache.load.RemoteMediaStore$.save(MediaStore.scala:333)
	at au.org.ala.biocache.load.DataLoader$$anonfun$processMedia$1.apply(DataLoader.scala:323)
	at au.org.ala.biocache.load.DataLoader$$anonfun$processMedia$1.apply(DataLoader.scala:295)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at au.org.ala.biocache.load.DataLoader$class.processMedia(DataLoader.scala:295)
	at au.org.ala.biocache.load.DwCALoader.processMedia(DwCALoader.scala:95)
	at au.org.ala.biocache.load.DwCALoader$PersistConsumer.run(DwCALoader.scala:419)
	at java.lang.Thread.run(Thread.java:748)
aws-bstore-4b 2019-09-09 14:09:51,049 INFO : [DataLoader] - 10, >> last key : dr1411|1020580, UUID: , records per sec: 8.285004
```

**Comment by djtfmartin** [comment]
This is now fixed with this commit in the 2.4.6-SNAPSHOT.

https://github.com/AtlasOfLivingAustralia/biocache-store/commit/02794375d390f6c8979a547123e7be21bcea9938
