### ISSUE TITLE
NoSuchElementException in DwCACreator

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#344]
The latest changes to DwCACreator failed with a `NoSuchElementException` https://github.com/AtlasOfLivingAustralia/biocache-store/commit/92971f4943e831646fd3321582584ab1bd0b0972 :

```
aws-bstore-1b 2019-09-25 07:45:42,286 INFO : [Cassandra3PersistenceManager] - #######  Using full replication, so splitting token ranges based on node number 0
aws-bstore-1b 2019-09-25 07:45:42,286 INFO : [Cassandra3PersistenceManager] - #######  Total number of token ranges for cluster 1025
aws-bstore-1b 2019-09-25 07:45:42,293 INFO : [Cassandra3PersistenceManager] - Starting threads...number of callables 1025
aws-bstore-1b 2019-09-25 10:02:11,370 INFO : [Cassandra3PersistenceManager] - All threads have completed paging
aws-bstore-1b 2019-09-25 10:02:11,562 ERROR: [DwCACreator] - None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at au.org.ala.biocache.export.DwCACreator$$anonfun$main$2.apply(DwCACreator.scala:248)
	at au.org.ala.biocache.export.DwCACreator$$anonfun$main$2.apply(DwCACreator.scala:247)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at au.org.ala.biocache.export.DwCACreator$.main(DwCACreator.scala:247)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:130)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
Exception in thread "main" java.lang.RuntimeException: java.util.NoSuchElementException: None.get
	at au.org.ala.biocache.export.DwCACreator$.main(DwCACreator.scala:256)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:130)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at au.org.ala.biocache.export.DwCACreator$$anonfun$main$2.apply(DwCACreator.scala:248)
	at au.org.ala.biocache.export.DwCACreator$$anonfun$main$2.apply(DwCACreator.scala:247)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at au.org.ala.biocache.export.DwCACreator$.main(DwCACreator.scala:247)
	... 2 more
```

One of the field lists may not have the same contents as the other field lists.

It stalled at that point, so I manually killed the Jenkins job.

**Comment by djtfmartin** [comment]
Possibly caused by this record:

https://biocache.ala.org.au/occurrences/8affd9dd-f04a-40cf-879f-9da4278f4614

which doesnt have an entry in the collectory....

**Comment by djtfmartin** [comment]
This was the issue. Ive added a null guard but we should follow up and remove this record or add the entry back into collectory.
