### ISSUE TITLE
Invalid UUID string: null

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#356]
The following stacktrace (and non-termination) occurred during a recent jenkins job using the latest biocache-store-2.4.6-SNAPSHOT version https://github.com/AtlasOfLivingAustralia/biocache-store/commit/528978f4b93fc5a354cc22240009cbf2628845ea :

```
aws-bstore-4b 2019-11-22 14:50:41,879 INFO : [RemoteMediaStore] - Remote media store host recognised: https://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=null
aws-bstore-4b 2019-11-22 14:50:41,879 ERROR: [DataLoader] - Invalid UUID string: null
java.lang.IllegalArgumentException: Invalid UUID string: null
	at java.util.UUID.fromString(UUID.java:194)
	at au.org.ala.biocache.load.RemoteMediaStore$$anonfun$extractUUIDFromURL$1.apply(MediaStore.scala:346)
	at au.org.ala.biocache.load.RemoteMediaStore$$anonfun$extractUUIDFromURL$1.apply(MediaStore.scala:343)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at au.org.ala.biocache.load.RemoteMediaStore$.extractUUIDFromURL(MediaStore.scala:343)
	at au.org.ala.biocache.load.RemoteMediaStore$.save(MediaStore.scala:287)
	at au.org.ala.biocache.load.DataLoader$$anonfun$processMedia$1.apply(DataLoader.scala:323)
	at au.org.ala.biocache.load.DataLoader$$anonfun$processMedia$1.apply(DataLoader.scala:295)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at au.org.ala.biocache.load.DataLoader$class.processMedia(DataLoader.scala:295)
	at au.org.ala.biocache.load.DwcCSVLoader.processMedia(DwcCSVLoader.scala:85)
	at au.org.ala.biocache.load.DataLoader$class.load(DataLoader.scala:256)
	at au.org.ala.biocache.load.DwcCSVLoader.load(DwcCSVLoader.scala:85)
	at au.org.ala.biocache.load.DwcCSVLoader.loadFile(DwcCSVLoader.scala:279)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$loadDirectory$1.apply(DwcCSVLoader.scala:138)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$loadDirectory$1.apply(DwcCSVLoader.scala:136)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.DwcCSVLoader.loadDirectory(DwcCSVLoader.scala:136)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:118)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:110)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.load.DwcCSVLoader.load(DwcCSVLoader.scala:110)
	at au.org.ala.biocache.load.Loader.load(Loader.scala:206)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:99)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:99)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.Loader$.main(Loader.scala:98)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:130)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
Exception in thread "main" java.lang.IllegalArgumentException: Invalid UUID string: null
	at java.util.UUID.fromString(UUID.java:194)
	at au.org.ala.biocache.load.RemoteMediaStore$$anonfun$extractUUIDFromURL$1.apply(MediaStore.scala:346)
	at au.org.ala.biocache.load.RemoteMediaStore$$anonfun$extractUUIDFromURL$1.apply(MediaStore.scala:343)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at au.org.ala.biocache.load.RemoteMediaStore$.extractUUIDFromURL(MediaStore.scala:343)
	at au.org.ala.biocache.load.RemoteMediaStore$.save(MediaStore.scala:287)
	at au.org.ala.biocache.load.DataLoader$$anonfun$processMedia$1.apply(DataLoader.scala:323)
	at au.org.ala.biocache.load.DataLoader$$anonfun$processMedia$1.apply(DataLoader.scala:295)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at au.org.ala.biocache.load.DataLoader$class.processMedia(DataLoader.scala:295)
	at au.org.ala.biocache.load.DwcCSVLoader.processMedia(DwcCSVLoader.scala:85)
	at au.org.ala.biocache.load.DataLoader$class.load(DataLoader.scala:256)
	at au.org.ala.biocache.load.DwcCSVLoader.load(DwcCSVLoader.scala:85)
	at au.org.ala.biocache.load.DwcCSVLoader.loadFile(DwcCSVLoader.scala:279)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$loadDirectory$1.apply(DwcCSVLoader.scala:138)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$loadDirectory$1.apply(DwcCSVLoader.scala:136)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.DwcCSVLoader.loadDirectory(DwcCSVLoader.scala:136)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:118)
	at au.org.ala.biocache.load.DwcCSVLoader$$anonfun$load$1.apply(DwcCSVLoader.scala:110)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.load.DwcCSVLoader.load(DwcCSVLoader.scala:110)
	at au.org.ala.biocache.load.Loader.load(Loader.scala:206)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:99)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:99)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.Loader$.main(Loader.scala:98)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:130)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
```

`http://aws-scjenkins.ala:9193/job/Cloud%20Infrastructure/job/BSTORE/job/Parameterised%20Load/6675/console`

**Comment by peggynewman** [comment]
@ansell any further info about how we might be able to reproduce this problem? 
Otherwise we might close this.

**Comment by ansell** [comment]
@peggynewman No, there were no other hints in the log file about why it was attempting to work on a null value. Closing.
