### ISSUE TITLE
Exception thrown during indexing

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-store#40]
2015-02-20 22:55:39,209 ERROR: [SolrIndexDAO] - Unexpected character ('o' (code 111)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@132aecd9; line: 1, column: 2]
org.codehaus.jackson.JsonParseException: Unexpected character ('o' (code 111)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@132aecd9; line: 1, column: 2]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1291)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
	at org.codehaus.jackson.impl.ReaderBasedParser._handleUnexpectedValue(ReaderBasedParser.java:628)
	at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:362)
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2432)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2389)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1609)
	at au.org.ala.biocache.util.Json$.toStringArray(Json.scala:75)
	at au.org.ala.biocache.index.IndexDAO$class.getOccIndexModel(IndexDAO.scala:314)
	at au.org.ala.biocache.index.SolrIndexDAO.getOccIndexModel(SolrIndexDAO.scala:29)
	at au.org.ala.biocache.index.SolrIndexDAO.indexFromMap(SolrIndexDAO.scala:360)
	at au.org.ala.biocache.index.IndexRunner$$anonfun$run$7.apply(IndexRecordMultiThreaded.scala:458)
	at au.org.ala.biocache.index.IndexRunner$$anonfun$run$7.apply(IndexRecordMultiThreaded.scala:446)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:341)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:333)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOver(CassandraPersistenceManager.scala:333)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOverAll(CassandraPersistenceManager.scala:469)
	at au.org.ala.biocache.index.IndexRunner.run(IndexRecordMultiThreaded.scala:446)
	at java.lang.Thread.run(Thread.java:745)
2015-02-20 22:55:39,233 ERROR: [IndexRunner] - Problem indexing record: rowKeyUnexpected character ('o' (code 111)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

**Comment by djtfmartin** [comment]
closing -  can reproduce
