### ISSUE TITLE
Image extension problem with upppercased file extensions

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-store#69]
An uppercase image file extension eg ".JPG" causes the following exception to be thrown.

```
2015-08-11 15:50:34,322 ERROR: [DataLoader] - Some(null) (of class scala.Some)
scala.MatchError: Some(null) (of class scala.Some)
        at au.org.ala.biocache.model.Multimedia$.findMimeType(Multimedia.scala:36)
        at au.org.ala.biocache.model.Multimedia$.create(Multimedia.scala:66)
        at au.org.ala.biocache.load.DwCALoader$$anonfun$loadMultimedia$1.apply(DwCALoader.scala:342)
        at au.org.ala.biocache.load.DwCALoader$$anonfun$loadMultimedia$1.apply(DwCALoader.scala:339)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at au.org.ala.biocache.load.DwCALoader.loadMultimedia(DwCALoader.scala:339)
        at au.org.ala.biocache.load.DwCALoader.loadArchive(DwCALoader.scala:263)
        at au.org.ala.biocache.load.DwCALoader$$anonfun$load$1.apply(DwCALoader.scala:114)
        at au.org.ala.biocache.load.DwCALoader$$anonfun$load$1.apply(DwCALoader.scala:105)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at au.org.ala.biocache.load.DwCALoader.load(DwCALoader.scala:105)
        at au.org.ala.biocache.load.Loader.load(Loader.scala:155)
        at au.org.ala.biocache.load.IngestTool$.ingestResource(IngestTool.scala:101)
        at au.org.ala.biocache.load.IngestTool$$anonfun$main$1.apply(IngestTool.scala:54)
        at au.org.ala.biocache.load.IngestTool$$anonfun$main$1.apply(IngestTool.scala:51)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at au.org.ala.biocache.load.IngestTool$.main(IngestTool.scala:51)
        at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:126)
        at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
Exception in thread "main" scala.MatchError: Some(null) (of class scala.Some)
        at au.org.ala.biocache.model.Multimedia$.findMimeType(Multimedia.scala:36)
        at au.org.ala.biocache.model.Multimedia$.create(Multimedia.scala:66)
        at au.org.ala.biocache.load.DwCALoader$$anonfun$loadMultimedia$1.apply(DwCALoader.scala:342)
        at au.org.ala.biocache.load.DwCALoader$$anonfun$loadMultimedia$1.apply(DwCALoader.scala:339)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at au.org.ala.biocache.load.DwCALoader.loadMultimedia(DwCALoader.scala:339)
        at au.org.ala.biocache.load.DwCALoader.loadArchive(DwCALoader.scala:263)
        at au.org.ala.biocache.load.DwCALoader$$anonfun$load$1.apply(DwCALoader.scala:114)
        at au.org.ala.biocache.load.DwCALoader$$anonfun$load$1.apply(DwCALoader.scala:105)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at au.org.ala.biocache.load.DwCALoader.load(DwCALoader.scala:105)
        at au.org.ala.biocache.load.Loader.load(Loader.scala:155)
        at au.org.ala.biocache.load.IngestTool$.ingestResource(IngestTool.scala:101)
        at au.org.ala.biocache.load.IngestTool$$anonfun$main$1.apply(IngestTool.scala:54)
        at au.org.ala.biocache.load.IngestTool$$anonfun$main$1.apply(IngestTool.scala:51)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at au.org.ala.biocache.load.IngestTool$.main(IngestTool.scala:51)
        at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:126)
        at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
```

**Comment by jholetschek** [comment]
The problems seems to occure also with lower case extensions, e.g. http://media.bgbm.org/erez/erez?cmd=get&src=specimentool/Animals/Birds/Corvus_corax_corax_2015-01-18_whk_DE_Berlin_1879.jpg

**Comment by charvolant** [comment]
This appears to be caused by the DwCA loader not handling null values properly in the image extension data. 

@jholetschek Any chance of getting the line for that image in the image extension file, so that I can confirm this?

(There's also a bug where extra .s in the filename are not handled correctly when extension getting. I'll fix that at the same time.)

**Comment by jholetschek** [comment]
Fields description, format, license and rightsHolder are empty. Apparently I can't upload zip or txt files, so I paste it in here. First is the list of fields, second the first row in the file

"catalogNumber","identifier","description","format","created","creator","license","rightsHolder"

"02472400-3787-47f8-ba7b-ec9cb8ae9400","http://media.bgbm.org/erez/erez?cmd=get&src=specimentool/Animals/Birds/Corvus_corax_corax_2015-01-18_whk_DE_Berlin_1879.jpg",,,"2015-01-18","W.-H. Kusber",,

**Comment by djtfmartin** [comment]
Ive tested @jholetschek DwC-A file with the patch and it all look good :)
Thanks @charvolant for producing the patch so quickly.

This has been released as version 1.5.6

**Comment by jholetschek** [comment]
Cool... thanks both!
This means I can re-run the ansible scripts and I should get this patch?

**Comment by djtfmartin** [comment]
Yes.

If you rerun with

```
--tags "biocache-cli"
```

then it should do all it needs to do.
