### ISSUE TITLE
Exception thrown in Sampling

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-store#86]
The following exception is thrown at the end of ```biocache sample -dr dr1```.
Im not sure what the implications are.

```
2015-10-14 16:18:02,898 INFO : [BulkProcessor] - Finished loading: /data/tmp/sampling-dr112.txt in 42ms
Exception in thread "Thread-9" java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2052)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at au.org.ala.biocache.tool.LoadSamplingConsumer.run(Sampling.scala:603)`
```

cc @adam-collins

**Comment by adam-collins** [comment]
No impact other than log messages. Cleaned it up.
